### PR TITLE
For May august contibution Folder

### PR DESCRIPTION
**Pull request by Radhika-Saini**
A copy of Task 2 for May august contibution Folder.

### CODE REVIEW

**Comment by ps-19** [comment]
This PR would cause a conflict with https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/66 . As after reverting the files your data will only be avaliable in outreachy-2022 folder not in may-aug-contribution.

**Comment by jafsia** [comment]
Try to solve the conflicting files issue

**Comment by jafsia** [comment]
This branch has conflicting files

**Comment by Radhika-Saini** [comment]
Please don't merge this PR.

**Pull request closed without merging**
