### PR TITLE
Task 0 done final

### PR DESCRIPTION
**Pull request by PetraAG**

### CODE REVIEW

**Comment by ps-19** [comment]
This PR would cause a conflict with https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/66 . As after reverting the files your data will only be avaliable in outreachy-2022 folder not in may-aug-contribution.

**Comment by ps-19** [comment]
https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/79 closes this PR.

**Comment by ps-19** [comment]
You can close this PR once #79 is merged.

**Comment by PetraAG** [comment]
Okay

**Comment by jafsia** [comment]
There are conflicting files .

**Comment by ps-19** [comment]
@PetraAG you can close the PR now. Task done successfully.

**Comment by PetraAG** [comment]
closed the PR. Thanks mentor @jafsia and @ps-19

**Pull request closed without merging**
