### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by ps-19**
Overview :
- Worked to improve the inclusivity of docs
- Made Docs beginner-friendly
- Removed Grammatical mistakes
- Removed code errors

### CODE REVIEW

**Comment by ps-19** [comment]
@jafsia sir please review this PR.

**Comment by ps-19** [comment]
I have a question is it necessary to know french to get accepted as an intern ?

**Comment by jafsia** [comment]
No french, outreachy language is french

Le sam. 16 avr. 2022 à 18:46, Priyansh Singh ***@***.***> a
écrit :

**Comment by jafsia** [comment]
Great job

**Comment by ps-19** [comment]
Thank you sir.

**Comment by ps-19** [comment]
Task-1
image
image
image
image
image
image
image


image
image

**Comment by ps-19** [comment]
Task-1 Method-2

image
image
image
image

**Pull request merged**
