### PR TITLE
pertaAG

### PR DESCRIPTION
**Pull request by ps-19**
Submitting the PR on behalf of pertaAG as her PR got into conflict with main repository.
This PR completes task of PR #[64](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/64)

signoff:
Name: Agien Petra Ukeh
Email: Not Provided

Updated files:
- https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task0.md
- https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task1.md
- https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task2.md

=============================================================

Typhoid BOT: https://ps-19.github.io/bot/

Advanced Task

1) Task-1
     a) [Demo Video](https://www.loom.com/share/d0ac40ef64f046288f27649eb39c4d46)
     b) [Demo Video](https://www.loom.com/share/3e580de38647438aa80124f6105f5d43)
     c) [Dataset](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Priyansh_Singh/Task1/Method-3/county-outpatient-morbidity-for-patients-below-5-years-of-age-in-2013-detailed-csv-1.csv)

2) Task-2
     a) [Demo Video](https://www.loom.com/share/f3da00da698e42b488c4c6fd1b2f6408)
     b) [Complete Documentation](https://docs.google.com/document/d/1pjb2QiqUWI4pi82_QNUR0iR-bpUoeXHQHzLhDHVscsg/edit?usp=sharing)
     
     Complete App:
          i) [Figma](https://www.figma.com/file/OmiDLNA8nqsAzeJtrw15mU/Priyansh-Singh-Typoid-Fever?node-id=0%3A1)
          ii) [Technical Documentation](https://docs.google.com/document/d/1Lf84SVycahVKrOVtYRzmsEAmLgT2sK8yNhAP6Wfh6m4/edit?usp=sharing)

     App Typhoid Prediction Feature:
          i) [Figma](https://www.figma.com/file/9aZzvnHegYajVwN8r3KxAK/Typhoid-Fever-Prediction?node-id=0%3A1)
          ii) [Technical Documentation](https://docs.google.com/document/d/1dJfqPvf0Vm4xr14QiVF-CQ-DQST4SKTbIvMQ53wN6nw/edit?usp=sharing)

### CODE REVIEW

**Comment by ps-19** [comment]
Respected @jafsia sir please merge this PR i have to submit another PR which will add functionality to mine contribution folder.

**Comment by jafsia** [comment]
Will merge

Le mar. 19 avr. 2022 à 12:51, Priyansh Singh ***@***.***> a
écrit :

**Comment by PetraAG** [comment]
> Submitting the PR on behalf of pertaAG as her PR got into conflict with main repository. This PR completes task of PR #[64](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/64)
> 
> signoff: Name: Agien Petra Ukeh Email: Not Provided
> 
> Updated files:
> 
> * https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task0.md
> * https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task1.md
> * https://github.com/ps-19/Mboalab_Outreachy-May-Aug-2022/blob/main/May-August-Contributions/Agien_Petra_ukeh/Task2.md

Thank you @ps

**Comment by ps-19** [comment]
This PR is in support of community and help in it's building and provide base to learn, tackle issues they are facing.

**Comment by ps-19** [comment]
About Me:
I am an undergraduate student of IT. In my first year I started doing competitive coding and still today I am doing competitive coding (https://www.stopstalk.com/user/profile/ps_19).

In my second year I got to know about open source from GSoC and outreachy internship, I started contributing to repositories like kubernetes-client, Pycharm, Cherrypy, LoginRadius, Cataclysm-DDA, LLVM, Fedora etc. I have a lot of PRs merged into these repositories(https://github.com/ps-19).

In my third year I am doing software development using Nodejs, Express, React, MongoDB, Django etc. and made some projects on them and right now I am working on some projects on Deep Learning (github.com/ps-19). I am doing competitive coding and contributing to open source as well, I have experience in complete(backend and frontend) software development and web development using MERN stack and other techs.

My github account is https://github.com/ps-19 and my resume could be found here https://bit.ly/3IiJ6XD, email is ([priyansh.singh100@gmail.com](mailto:priyansh.singh100@gmail.com)) and portfolio here https://ps-19.github.io/Portfolio/.

**Pull request merged**
