### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by ps-19**
Updated the readme.md file.

This PR do:
- Increases the inclusivity of the docs
- Improves user experience
- Updates broken links & code

image
image

### CODE REVIEW

**Comment by jafsia** [comment]
Your branch has conflicting files and can't be merged.

**Comment by jafsia** [comment]
Conflicting files

**Comment by ps-19** [comment]
@jafsia sir done!!

**Comment by ps-19** [comment]
Branch have certain serious so closing the PR.

**Comment by ps-19** [comment]
<div id="top" align="center">

Awesome Badge
Star Badge
<a href="https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/stargazers">Stars Badge</a>
<a href="https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/network/members">Forks Badge</a>
<a href="https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pulls">Pull Requests Badge</a>
<a href="https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/issues">Issues Badge</a>
  
  Mboalab
  
<a href="https://twitter.com/LabMboa" > </a>
<a href="https://www.mboalab.africa/">Join Community Badge</a>

  [](https://www.mboalab.africa/) &nbsp; [](https://twitter.com/LabMboa)  &nbsp; [](https://www.linkedin.com/in/)  &nbsp; [](https://www.facebook.com/mboalab/)  &nbsp; [](https://www.instagram.com/)  &nbsp;  [](mailto:thomasmboa@gmail.com)
  
  </div>
  
# Mboalab

Mboalab is an open and collaborative space located in the village of Mefou-Assi, Yaounde, Cameroon. The aim of Mboalab is to catalyse sustainable development and improve people's living conditions through open science. We bring together researchers, scholars, educationists, policy makers and the general public to discuss, conceive and implement projects responding to the health, economic and social needs of the community, such as the coronavirus pandemic. Our approach focuses on the integration of local knowledge by centering the local community especially women.

# Background & Objective

**The aim of Mboalab is to catalyse sustainable local development and improve people’s living conditions through open science.**

To this end, the main missions of Mboalab are as follows: 

- provide community and lifelong education for the population, as well as formal education for the younger generations. 
- serve as a platform for exchanges on issues related to local context; mediate between local communities and academia. 
- propose solutions that meet the needs of communities, using local knowledge and open digital technologies.
- raise public awareness of environmental issues.
- facilitate access to basic health care.

# Know More About Us

### Lab Tour
-  You can take a tour of our lab [here](https://www.youtube.com/watch?v=Tfx-C--iELU).
  
### Key Collaborations
- [Open Bioeconomy Lab](https://openbioeconomy.org/)
- [Africa Open Science & Hardware](https://africaosh.com/)

# Project

## COV19CommunityKITs

We are primarily working on a project to support the mass production,  packaging in kits and distribution of open-source preventive equipments in remote areas. To know more about project, please [visit](https://app.jogl.io/project/217/COV19CommunityKITs).

### Skill Required
- [Open source](https://app.jogl.io/search/projects?refinementList[skills][0]=Open%20source)
- [Engineer software & hardware](https://app.jogl.io/search/projects?refinementList[skills][0]=Engineer%20software%20&%20hardware)
- [Project documentation](https://app.jogl.io/search/projects?refinementList[skills][0]=Project%20documentation)
- [Open research](https://app.jogl.io/search/projects?refinementList[skills][0]=Open%20research)
- [Diy](https://app.jogl.io/search/projects?refinementList[skills][0]=Diy)
- [Biochemistry](https://app.jogl.io/search/projects?refinementList[skills][0]=Biochemistry)
- [Project management](https://app.jogl.io/search/projects?refinementList[skills][0]=Project%20management%20skill)

## Our Moto:

In line with Outreachy’s guideline, the focus of our project is to prioritise the learning process and applicants' self-development over skill acquisition. 
Both applicants with or without previous experience in open-source contributions and complete beginners are welcome to participate and contribute. 

>**_Our main objective is to provide applicants with notions on open-source contributions and spirit, as well as with basics and advanced skills needed to complete the project;_**

## How to contribute to the project?
Applicants can contribute to this project through the [project repository](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022) on GitHub. 
Check the Contributions Guidelines and the list of details via [Technical Documentation](https://docs.google.com/document/d/1fzB-AcfYNnsvqBlwyJZJR1SfuvpjYxxpONnv13bPGqg/edit?usp=sharing)

## Mentor attribution
Each project’s Starter Task is supervised by a specific mentor. Applicants desiring to contribute to a specific task should get in touch with the assigned mentor. 
Information about the assigned mentor can be found in the task’s descriptions. Information about Mboalab community Mentors can be found [here](/Meet%20the%20Mentors).
See the [Meet the Mentors](/Meet%20the%20Mentors) Folder. Feel free to reach out [Bido](https://github.com/Bido) and [Nodira](https://github.com/nodira) for more guidance and details.

**Pull request closed without merging**
