### PR TITLE
fix: Broken Links in README.md #83

### PR DESCRIPTION
**Pull request by tejaswari7**
updated broken links in readme
@jafsia please review the PR

### CODE REVIEW

**Comment by jafsia** [comment]
Ok will review it

Le ven. 22 avr. 2022 à 10:06, tejaswari7 ***@***.***> a
écrit :

**Comment by jafsia** [comment]
solve conflicting files

**Comment by tejaswari7** [comment]
image
It's highlighting this part of code. I tried to edit it but it didn't helped.
can you suggests the correct way to resolve it!!

**Comment by jafsia** [comment]
Ok, I'll check it out.

Le ven. 22 avr. 2022 à 19:33, tejaswari7 ***@***.***> a
écrit :

**Comment by tejaswari7** [comment]
I tried to resolved it, hope its good to go!!

**Pull request merged**
