### PR TITLE
Resolved Conflict

### PR DESCRIPTION
**Pull request by ps-19**
Please resolve issue#[76](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/issues/76) before merging this request.

### CODE REVIEW

**Comment by jafsia** [comment]
Good job ps

**Comment by ps-19** [comment]
> Good job ps

Thank you sir!!
My name is **Priyansh Singh** (ps).

**Comment by ps-19** [comment]
image
image
image
image
image
image
image


image
image

**Comment by ps-19** [comment]
Tesk-1 Method-2

Web Scrapping and Web Crawling.

image
image
image
image

**Comment by ps-19** [comment]
Task-1
Method-3

image
image
image

**Comment by ps-19** [comment]
image
image
image
image
image
image

**Pull request merged**
