### PR TITLE
Add Ginika Jemeni Task0.md file

### PR DESCRIPTION
**Pull request by GinikaJ**
I added Task0.md file under Outreachy-2022 folder according to first task and updated README.md

### CODE REVIEW

**Comment by jafsia** [comment]
Can't be merged. Resolve conflicting files issue first.

**Comment by GinikaJ** [comment]
> Can't be merged. Resolve conflicting files issue first.


Thanks. I've resolved the issue.

**Comment by jafsia** [comment]
The issue is still there.

**Comment by GinikaJ** [comment]
> The issue is still there.

I've resolved it. Thank you.

**Pull request merged**
