### PR TITLE
Added New Functionalities

### PR DESCRIPTION
**Pull request by ps-19**
PR added following properties :
- Added Method-3 in Task-1
- Added Figmas.
- Added Technical Documentation for better visualisation and understanding.
- Added Demo Videos.

Note: All resources are kept private till contribution time to avoid [plagiarism](https://en.wikipedia.org/wiki/Plagiarism). It will made visible after contribution period is over.

### CODE REVIEW

**Comment by ps-19** [comment]
@jafsia sir please review the PR.

**Comment by jafsia** [comment]
Thanks, i will review it.

Le mar. 19 avr. 2022 à 21:30, Priyansh Singh ***@***.***> a
écrit :

**Comment by ps-19** [comment]
Respected @jafsia sir please merge the PR.

**Comment by ps-19** [comment]
image
image
image
image
image
image
image


image
image

**Comment by ps-19** [comment]
Task-1 method 3

image
image
image

**Comment by ps-19** [comment]
Task-1 Method-2

image
image
image





image

**Comment by ps-19** [comment]
https://ps-19.github.io/bot/

**Pull request merged**
